(* ****** ****** *)
(* ****** ****** *)
(*
HX-2026-08-22:
Sat Aug 22
09:20:42 AM EDT 2026
Generated by ChatGPT!
*)
(* ****** ****** *)
(* ****** ****** *)
//
(*
** ATS3 / ATS-Xanadu
**
** Generate all permutations of a list.
**
** The permutations are ordered according to the positions of
** the elements in the original list.
**
** For example:
**
** [a,b,c]
**
** produces:
**
** [a,b,c]
** [a,c,b]
** [b,a,c]
** [b,c,a]
** [c,a,b]
** [c,b,a]
**
** Element values are never compared. *)
//
(* ****** ****** *)
(* ****** ****** *)
#staload UN =
"prelude/SATS/unsfx00.sats"
(* ****** ****** *)
(* ****** ****** *)
//
#include
"prelude/HATS/prelude_dats.hats"
#include
"prelude/HATS/prelude_JS_dats.hats"
#include
"prelude/HATS/prelude_NODE_dats.hats"
//
(* ****** ****** *)
(* ****** ****** *)
//
fun
<a:t0>
list_permutations
(xs: list(a)): list(list(a)) =
(
  list_make_fwork<list(a)>(
    lam emit =>
    let
      fun
      aux
      (xs: list(a), pref: list(a)): void =
      (
        case+ xs of
        | list_nil() => emit(pref)
        | list_cons(_, _) =>
            let
              val choices =
                list_1choose$split_lstrm<a>(xs)
              val () =
                strm_vt_foritm0
                (
                  choices,
                  lam choice =>
                    aux(
                      list_vt2t(choice.1), list_extend(pref, choice.0)
                    )
                )
            in
              ()
            end
      )
    in
      aux(xs, list_nil())
    end
  )
)
//
(* ****** ****** *)
(* ****** ****** *)
//
val xs = list_3val<sint>(1, 2, 3)
//
val () = printsln
("permutations[", xs, "] = ", list_permutations(xs))
//
(* ****** ****** *)
(* ****** ****** *)
//
(***********************************************************************)
(* end of [ATS3/XANADU_srcgen2_xats2js_srcgen1_TEST_test13_xats2js.dats] *)
(***********************************************************************)
