(* ****** ****** *)
(* ****** ****** *)
(*
HX-2026-08-22:
Sat Aug 22
11:38:59 AM EDT 2026
Generated by ChatGPT!
Please see the error
in the generated code
that needs to be fixed!
//
HX-2026-08-22:
It took me 30 minutes
to locate and fix the bug.
I then pointed out the issue
t ChatGPT; and it was able to
fix the bug immediately!
//
*)
(* ****** ****** *)
(* ****** ****** *)
#staload UN =
"prelude/SATS/unsfx00.sats"
(* ****** ****** *)
(* ****** ****** *)
//
#include
"prelude/HATS/prelude_dats.hats"
#include
"prelude/HATS/prelude_JS_dats.hats"
#include
"prelude/HATS/prelude_NODE_dats.hats"
//
(* ****** ****** *)
(* ****** ****** *)
(*
** ATS3 / ATS-Xanadu
**
** All solutions to the 8-queens problem as a lazy linear stream.
**
** A solution is represented as:
**
**   [c0,c1,c2,c3,c4,c5,c6,c7]
**
** where ci is the column occupied by the queen in row i.
**
** Columns are tried from 0 through 7, so solutions are generated
** in lexicographic order of their column representations.
*)
(* ****** ****** *)
(* Is a proposed queen position safe? *)
(* ****** ****** *)
//
fun
queen_safe
(
  row: int,
  col: int,
  qs: list(int)
) : bool =
let
  fun
  loop
  (
    r: int,
    qs: list(int)
  ) : bool =
  (
    case+ qs of
    | list_nil() => true
    | list_cons(q, qs) =>
        let
          val dr = r + 1
          // HX-2026-08-22:
          // ChatGPT error!!!
          // val dr = row - r
          val dc =
            if col >= q
            then col - q else q - col
        in
          if // if
          (col = q)
          then false
          else if (dr = dc) then false else loop(r + 1, qs)
        end
  )
in
  loop(0, qs)
end
//
(* ****** ****** *)
(* Generate all solutions from a given row. *)
(* ****** ****** *)
//
fun
eight_queens
(): list(int) =
let
  (*
  ** [solve_row row qs]
  **
  ** [qs] contains the columns selected for rows
  ** 0 .. row-1.
  **
  ** We try columns from 0 through 7.  Consequently,
  ** the first solution is deterministic.
  *)
  fun
  solve_row
  (
    row: int,
    qs: list(int)
  ): list(int) =
  (
    if row = 8
    then
      list_reverse<int>(qs)
    else
      try_col(row, 0, qs)
  )
  (*
  ** Try each possible column in the current row.
  *)
  and
  try_col
  (
    row: int,
    col: int,
    qs: list(int)
  ): list(int) =
    if col = 8
    then
      list_nil<int>()
    else
      if queen_safe(row, col, qs)
      then
        let
          val qs1 =
            list_cons<int>(col, qs)

          val result =
            solve_row(row + 1, qs1)
        in
          case+ result of
          | list_nil() =>
              try_col(row, col + 1, qs)

          | list_cons(_, _) =>
              result
        end
      else
        try_col(row, col + 1, qs)
in
  solve_row(0, list_nil<int>())
end
//
(* ****** ****** *)
(* ****** ****** *)
//
fun
verify_solution
(
  qs: list(int)
): bool =
let
  fun
  loop
  (
    row: int,
    qs: list(int)
  ): bool =
    case+ qs of
    | list_nil() =>
        row = 8
    | list_cons(col, qs) =>
      (
        if col < 0 then false else
        if col >= 8 then false else
        if queen_safe(row, col, qs) then loop(row + 1, qs) else false
      )
in
  loop(0, qs)
end
//
(* ****** ****** *)
(* ****** ****** *)
//
fun
test_expected_solution(): void =
let
  val actual =
    eight_queens()

  val expected =
    list_make_3val<int>(0, 4, 7)

  val expected =
    list_extend<int>(expected, 5)

  val expected =
    list_extend<int>(expected, 2)

  val expected =
    list_extend<int>(expected, 6)

  val expected =
    list_extend<int>(expected, 1)

  val expected =
    list_extend<int>(expected, 3)

  val ok =
    list_equal<int>(actual, expected)
(*    
  val () =
  printsln("test_expected: actual = ", actual)
  val () =
  printsln("test_expected: expected = ", expected)
*)
in
  if ok
  then
  printsln("test_expected_solution: PASS")
  else
  printsln("test_expected_solution: FAIL")
end
//
(* ****** ****** *)
//
fun
test_validity(): void =
let
  val solution =
    eight_queens()

  val ok =
    verify_solution(solution)
in
  if ok
  then printsln("test_validity: PASS")
  else printsln("test_validity: FAIL")
end
//
(* ****** ****** *)
//
fun
test_known_solution(): void =
let
  val solution =
    list_make_3val<int>(0, 4, 7)

  val solution =
    list_extend<int>(solution, 5)

  val solution =
    list_extend<int>(solution, 2)

  val solution =
    list_extend<int>(solution, 6)

  val solution =
    list_extend<int>(solution, 1)

  val solution =
    list_extend<int>(solution, 3)

  val ok =
    verify_solution(solution)
in
  if ok
  then printsln("test_known_solution: PASS")
  else printsln("test_known_solution: FAIL")
end
//
(* ****** ****** *)
(* ****** ****** *)
//
val () =
test_expected_solution()
val () = test_validity()
val () = test_known_solution()
//
(***********************************************************************)
(* end of [ATS3/XANADU_srcgen2_xats2js_srcgen1_TEST_test14_xats2js.dats] *)
(***********************************************************************)
