(* ****** ****** *)
(* ****** ****** *)
(*
HX-2026-08-22:
Sat Aug 22
09:20:42 AM EDT 2026
Generated by ChatGPT!
*)
(* ****** ****** *)
(* ****** ****** *)
#staload UN =
"prelude/SATS/unsfx00.sats"
(* ****** ****** *)
(* ****** ****** *)
//
#include
"prelude/HATS/prelude_dats.hats"
#include
"prelude/HATS/prelude_JS_dats.hats"
#include
"prelude/HATS/prelude_NODE_dats.hats"
//
(* ****** ****** *)
(* ****** ****** *)
//
fun
<a:type>
list_permutations
(xs: list(a)): list(list(a)) =
(
case+ xs of
|
list_nil () =>
list_cons(list_nil (), list_nil ())
|
list_cons (x, xs) =>
let
  val ps = list_permutations(xs)
in//let
list_list$concat
(
list_map(
  ps
, lam p => insert_everywhere(x, p))
)
end
) where//end-of-[list_permutations(xs)]
{
//
fun
insert_everywhere
(x: a, xs: list(a)): list(list(a)) =
(
case+ xs of
|
list_nil () =>
list_cons
(
list_cons
(x, list_nil()), list_nil())
|
list_cons(y, ys) =>
let
val rest =
insert_everywhere(x, ys)
val here = list_cons(x, xs)
val after =
list_map
(rest, lam zs => list_cons(y, zs))
in
  list_cons(here, after)
end
)(*where*)//end-of-[insert_everywhere(xs)]
//
}(*where*)//end-of-[list_permutations(xs)]
//
(* ****** ****** *)
(* ****** ****** *)
//
val xs = list_3val<sint>(1, 2, 3)
//
val () = printsln
("permutations[", xs, "] = ", list_permutations(xs))
//
(* ****** ****** *)
(* ****** ****** *)
//
(***********************************************************************)
(* end of [ATS3/XANADU_srcgen2_xats2js_srcgen1_TEST_test12_xats2js.dats] *)
(***********************************************************************)
